####################################################################
# SCRIPT PURPOSE 
####################################################################

# The purpose of this script is to plot PRMS output from the statvar
# file and from the new subbasin module.  


####################################################################
# SCRIPT USE INSTRUCTIONS
####################################################################

# To use this script:
# 1) Place this script in a folder containing a "gsflow" folder, an "R_outputs" folder,
#    and another script entitled "PRMS_output_statvar_nsub_plotting_function.R".  Make 
#    sure the folder structure within the "gsflow" and "R_outputs" folders are set up in 
#    the same way as run_048.  (In other words, all of the same sub-folders need to be 
#    present in your folder structure.)
# 2) Set the working directory on line 72 below where it says SET WORKING DIRECTORY HERE.
# 3) Set the run folder on line 82 where it says CHOOSE WHICH RUN TO PLOT HERE.
# 3) Scroll down to the CHOOSE PLOTTING OUTPUT HERE section of this script and change 
#    the values as desired.
# 3) Scroll down to the CHOOSE SUBBASIN OUTPUT HERE section of this script and change 
#    the values as desired.
# 4) Use Microsoft Excel to save the statvar.dat file as "statvar.csv" and save it 
#    in the same folder as statvar.dat.
# 5) Highlight everything in this script and hit run.  It'll take a few minutes.
# 6) The plots and tables generated by the script are stored in the "R_outputs" folder.


####################################################################
# set up 
####################################################################

# clear workspace
rm(list=ls())

# install packages
# install.packages("plyr")
# install.packages("ggplot2")
# install.packages("stringr")
# install.packages("reshape2")
# install.packages("dplyr")
# install.packages("plotly")
# install.packages("devtools")
# install.packages("leaflet")
# install_github("rstudio/leaflet")
# install.packages("zoo")
# devtools::install_github("guiastrennec/ggplus")
# install.packages("scales")
# install.packages("rstudioapi")


# load libraries
library(plyr)
#library(dplyr)
library(ggplot2)
library(reshape2)
library(stringr)
#library(plotly)
#library(entropy)
#library(devtools)
#library(leaflet)
library(zoo)
#library(ggplus)
library(scales)
#library(rstudioapi)


# SET WORKING DIRECTORY HERE
# Set to current file location
setwd("C:/gsflow_onlyPRMS")




####################################################################
# CHOOSE WHICH RUN TO PLOT HERE 
#(THIS NEEDS TO BE FORMATTED EXACTLY LIKE THE FOLDER NAMES IN  
# THE PRMS OUTPUT FOLDER)
####################################################################
runFolder <- '0001'  




####################################################################
# CHOOSE PLOTTING OUTPUT HERE 
####################################################################

# The plots this script can generate are listed below:

# In particular, the script:
# 1) Plots for each subbasin: watershed average annual precipitation total, gauged average
#    annual precipitation total
# 2) Plots for each subbasin: distributed monthly precipitation, gauged monthly precipitation 
# 3) Plot for each subbasin: distributed annual precipitation, annual measured streamflow 
#    volume, annual simulated streamflow volume 
# 4) Plot for each subbasin: annual measured streamflow volume, annual simulated streamflow 
#    volume in acre-ft
# 5) Plot for each subbasin: annual streamflow components as bar plots along with runoff
#    (sub_gwflow, sub_interflow, sub_sroff, sub_cfs, runoff)
# 6) Plot for each subbasin: daily streamflow components as line plots
#    (sub_gwflow, sub_interflow, sub_sroff, sub_cfs)
# 7) Plot for each subbasin: annual streamflow components as grouped and stacked bar plots
#    (sub_gwflow, sub_interflow, sub_sroff, sub_cfs)
# 8) Plot for each subbasin: annual runoff ratios
# 9) Plots for each subbasin: distributed monthly precipitation, monthly measured streamflow 
#     volume, monthly simulated streamflow volume
# 10) Plot for each subbasin: distributed daily precipitation, simulated daily streamflow, 
#     measured daily streamflow (using line plots) 
# 11) Plot for each subbasin: distributed daily precipitation, simulated daily streamflow, 
#     measured daily streamflow (using line plots) - put precip on secondary y axis with axis 
#     reversed
# 12) Plots for the entire basin: the measured vs. simulated PPT/ET ratio 
#     (averaged over the period of record)
# 13) Plot the measured vs. simulated solar radiation
# 14) Plot annual water balance for each subwatershed (in inches)
# 15) Plot volumetric efficiency and Nash-Sutcliffe efficiency on daily flows
# 16) Plot volumetric efficiency and Nash-Sutcliffe efficiency on monthly mean flows summed over HY
# 17) Plot volumetric efficiency and Nash-Sutcliffe efficiency on monthly mean flows summed over
#     that month during study period
# 18) Plot volumetric efficiency and Nash-Sutcliffe efficiency on annual volumes
# 19) Plot correlation coefficient
# 20) Plot monthly precip totals and monthly mean simulated and observed flows
# 21) Plot for each subbasin: monthly mean observed and simulated flow averaged over all years
# 22) Plot for each subbasin: comparison of Dunnian vs. Hortonian HY volumes 
# 23) Plot for each subbasin: water balance (watershed precip vs. actual ET, runoff, storage) for HY volumes
# 24) Plot for each subbasin: flow components (streamflow vs. groundwater, interflow, surface flow) for HY volumes
# 25) Plot for each subbasin: flow duration curves for all years together; > 100 cfs and < 100 cfs separately
# 26) Plot for each subbasin: flow duration curves for each HY; > 100 cfs and < 100 cfs separately


# Set values of plots0#_OnOff to 0 or 1
# numbers in variable name correspond to the numbers in the list above
# 0 = don't plot, 1 = plot
plots01_OnOff <- 0
plots02_OnOff <- 0
plots03_OnOff <- 0
plots04_OnOff <- 1
plots05_OnOff <- 1
plots06_OnOff <- 1
plots07_OnOff <- 1
plots08_OnOff <- 1
plots09_OnOff <- 1
plots10_OnOff <- 0
plots11_OnOff <- 1
plots12_OnOff <- 1
plots13_OnOff <- 1
plots14_OnOff <- 1
plots15_OnOff <- 0
plots16_OnOff <- 0
plots17_OnOff <- 0
plots18_OnOff <- 0
plots19_OnOff <- 0
plots20_OnOff <- 1
plots21_OnOff <- 1
plots22_OnOff <- 1
plots23_OnOff <- 1
plots24_OnOff <- 1
plots25_OnOff <- 1
plots26_OnOff <- 1



plots_OnOff <- c(plots01_OnOff, 
                 plots02_OnOff, 
                 plots03_OnOff, 
                 plots04_OnOff, 
                 plots05_OnOff, 
                 plots06_OnOff, 
                 plots07_OnOff, 
                 plots08_OnOff, 
                 plots09_OnOff, 
                 plots10_OnOff, 
                 plots11_OnOff, 
                 plots12_OnOff, 
                 plots13_OnOff, 
                 plots14_OnOff,
                 plots15_OnOff, 
                 plots16_OnOff, 
                 plots17_OnOff, 
                 plots18_OnOff, 
                 plots19_OnOff, 
                 plots20_OnOff,
                 plots21_OnOff,
                 plots22_OnOff,
                 plots23_OnOff,
                 plots24_OnOff,
                 plots25_OnOff,
                 plots26_OnOff)





####################################################################
# CHOOSE SUBBASIN OUTPUT HERE 
####################################################################

# Set values of subbasin0#_OnOff to 0 or 1
# 0 = don't plot, 1 = plot
subbasin01_OnOff <- 0 # Indian Creek
subbasin02_OnOff <- 0 # San Antonio Creek at Indian Creek Rd
subbasin03_OnOff <- 1 # Arroyo Hondo
subbasin04_OnOff <- 1 # San Antonio Creek
subbasin05_OnOff <- 0 # Calaveras Creek
subbasin06_OnOff <- 1 # Alameda Creek above ACDD
subbasin07_OnOff <- 0 # Alameda Creek below ACDD
subbasin08_OnOff <- 0 # Alameda Creek below Calaveras Creek
subbasin09_OnOff <- 0 # Alameda Creek below Welch Creek
subbasin10_OnOff <- 0 # Alameda Creek near Niles
subbasin11_OnOff <- 0 # Alameda Creek above San Antonio Creek
subbasin12_OnOff <- 0 # Alameda Creek above Arroyo de la Laguna

subbasin_OnOff <- c(subbasin01_OnOff,
                    subbasin02_OnOff,
                    subbasin03_OnOff,
                    subbasin04_OnOff,
                    subbasin05_OnOff,
                    subbasin06_OnOff,
                    subbasin07_OnOff,
                    subbasin08_OnOff,
                    subbasin09_OnOff,
                    subbasin10_OnOff,
                    subbasin11_OnOff,
                    subbasin12_OnOff)








####################################################################
# RUN FUNCTION 
####################################################################

source("PRMS_output_statvar_nsub_plotting_function_04.R")

statvar_nsub_plotting(plots_OnOff, subbasin_OnOff, runFolder)






### to do ################################
# calculate everything using hydrologic year 

# download newest version of RStudio and R

# change all precip in palegoldenrod to yellow3 

# change all hydrologic months to normal months 

# remove redundancies